### ISSUE TITLE
Monterey login screen graphic glitches

### ISSUE THREAD

**Issue by KajtekKajtek** [osx86-ijb/Lenovo-ThinkCentre-m93p-Tiny-macOS-Monterey#1]
Hi
do you have same problems with login screen glitches?
https://www.tonymacx86.com/threads/monterey-login-screen-graphic-glitches.316782/
I see you use same cpu i5-4570T but your OS  shows gpu as 4400 not 4600????

Thank you for any help.

**Comment by osx86-ijb** [comment]
There is some graphical inconsistencies, but that's due to the nature of the Intel iGPU in general and the changes made to macOS in Big Sur and newer.

**Comment by KajtekKajtek** [comment]
Thank you for your answer. I asked because no glitches at all with Big Sur...only with Monterey.
Thank you very much.
